# Generated by Django 5.2.9 on 2026-06-23 12:41

from django.db import migrations


def populate_default_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    default_roles = [
        {'name': 'ADMIN', 'description': 'System Administrator with full access'},
        {'name': 'DOCTOR', 'description': 'Medical professional accessing patients and appointments'},
        {'name': 'RECEPTIONIST', 'description': 'Front desk personnel managing scheduling'},
    ]
    for role_data in default_roles:
        Role.objects.get_or_create(name=role_data['name'], defaults={'description': role_data['description']})

def reverse_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name__in=['ADMIN', 'DOCTOR', 'RECEPTIONIST']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_default_roles, reverse_code=reverse_roles),
    ]

