# Generated by Django 5.2.9 on 2026-06-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("OTP_VERIFIED", "OTP Verified"),
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_LOCKED", "User Locked"),
                    ("USER_UNLOCKED", "User Unlocked"),
                    ("USER_DELETED", "User Deleted"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_REMOVED", "Role Removed"),
                    ("USER_DISABLED", "User Disabled"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("SESSION_REVOKED", "Session Revoked"),
                    ("ROLE_SEEDED", "Role Seeded"),
                    ("INITIAL_ADMIN_CREATED", "Initial Admin Created"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("EMAIL_VERIFICATION_SENT", "Email Verification Sent"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                ],
                max_length=50,
            ),
        ),
    ]
