# Generated by Django 5.2.9 on 2026-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_specialization_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Experience (Years)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="qualification",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Qualification"
            ),
        ),
    ]
