# Generated by Django 5.2.9 on 2026-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_experience_user_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("OTP_VERIFIED", "OTP Verified"),
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_LOCKED", "User Locked"),
                    ("USER_UNLOCKED", "User Unlocked"),
                    ("USER_DELETED", "User Deleted"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_REMOVED", "Role Removed"),
                    ("USER_DISABLED", "User Disabled"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("SESSION_REVOKED", "Session Revoked"),
                    ("ROLE_SEEDED", "Role Seeded"),
                    ("INITIAL_ADMIN_CREATED", "Initial Admin Created"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("EMAIL_VERIFICATION_SENT", "Email Verification Sent"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("CONSULTATION_REQUEST_CREATED", "Consultation Request Created"),
                    ("APPOINTMENT_REQUEST_VIEWED", "Appointment Request Viewed"),
                    ("APPOINTMENT_REQUEST_APPROVED", "Appointment Request Approved"),
                    ("APPOINTMENT_REQUEST_REJECTED", "Appointment Request Rejected"),
                    ("PATIENT_MATCHING_STARTED", "Patient Matching Started"),
                    ("PATIENT_LINKED", "Patient Linked"),
                    ("PATIENT_CREATED", "Patient Created"),
                    ("PATIENT_UPDATED", "Patient Updated"),
                    ("PATIENT_DELETED", "Patient Deleted"),
                    ("PATIENT_EXPORTED", "Patient Exported"),
                    ("PATIENT_ASSIGNED_DOCTOR", "Patient Assigned Doctor"),
                    ("PATIENT_STATUS_CHANGED", "Patient Status Changed"),
                    ("PATIENT_SEARCHED", "Patient Searched"),
                    ("PATIENT_PREVIEW_VIEWED", "Patient Preview Viewed"),
                    ("PATIENT_PROFILE_VIEWED", "Patient Profile Viewed"),
                    ("PARENT_INFORMATION_UPDATED", "Parent Information Updated"),
                    ("CHILD_INFORMATION_UPDATED", "Child Information Updated"),
                    ("PATIENT_INFORMATION_UPDATED", "Patient Information Updated"),
                    ("PATIENT_TIMELINE_VIEWED", "Patient Timeline Viewed"),
                    ("APPOINTMENT_CREATED", "Appointment Created"),
                    ("APPOINTMENT_PREVIEWED", "Appointment Previewed"),
                    ("APPOINTMENT_SLOT_VALIDATED", "Appointment Slot Validated"),
                    ("DOCTOR_AVAILABILITY_VIEWED", "Doctor Availability Viewed"),
                    ("SLOTS_FETCHED", "Slots Fetched"),
                ],
                max_length=50,
            ),
        ),
    ]
