# Generated by Django 5.2.9 on 2026-06-26 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slot_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Slot Duration (Minutes)"
                    ),
                ),
                (
                    "clinic_start_time",
                    models.TimeField(verbose_name="Clinic Start Time"),
                ),
                ("clinic_end_time", models.TimeField(verbose_name="Clinic End Time")),
                (
                    "max_bookings_per_slot",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Max Bookings Per Slot"
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Buffer Minutes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Settings",
                "verbose_name_plural": "Appointment Settings",
                "db_table": "consultations_appointment_settings",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "appointment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Appointment Number"
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=20,
                        verbose_name="Appointment Type",
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("ADMIN_PANEL", "Admin Panel"),
                            ("RECEPTIONIST", "Receptionist"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Booking Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("COMPLETED", "Completed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="Appointment Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                ("reason_for_visit", models.TextField(verbose_name="Reason for Visit")),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "parent_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_appointments",
                        to="consultations.appointment",
                        verbose_name="Parent Appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "consultations_appointments",
                "ordering": ["-appointment_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="appointment_attachments/",
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Attachment",
                "verbose_name_plural": "Appointment Attachments",
                "db_table": "consultations_appointment_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(verbose_name="Note")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("DOCTOR_ONLY", "Doctor Only"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Note",
                "verbose_name_plural": "Appointment Notes",
                "db_table": "consultations_appointment_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "request_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Request Number"
                    ),
                ),
                (
                    "parent_first_name",
                    models.CharField(max_length=150, verbose_name="Parent First Name"),
                ),
                (
                    "parent_last_name",
                    models.CharField(max_length=150, verbose_name="Parent Last Name"),
                ),
                (
                    "relationship_to_child",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Relationship to Child",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=20, verbose_name="Mobile Number"),
                ),
                (
                    "alternate_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Alternate Mobile Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "child_first_name",
                    models.CharField(max_length=150, verbose_name="Child First Name"),
                ),
                (
                    "child_last_name",
                    models.CharField(max_length=150, verbose_name="Child Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Child Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=20,
                        verbose_name="Appointment Type",
                    ),
                ),
                ("primary_concern", models.TextField(verbose_name="Primary Concern")),
                ("preferred_date", models.DateField(verbose_name="Preferred Date")),
                (
                    "preferred_time_slot",
                    models.CharField(max_length=50, verbose_name="Preferred Time Slot"),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Notes"
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("ADMIN_PANEL", "Admin Panel"),
                            ("RECEPTIONIST", "Receptionist"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="WEBSITE",
                        max_length=20,
                        verbose_name="Booking Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Request",
                "verbose_name_plural": "Appointment Requests",
                "db_table": "consultations_appointment_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="consultations.appointmentrequest",
                verbose_name="Appointment Request",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("slot_date", models.DateField(verbose_name="Slot Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BOOKED", "Booked"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_slots",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Slot",
                "verbose_name_plural": "Appointment Slots",
                "db_table": "consultations_appointment_slots",
                "ordering": ["slot_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("COMPLETED", "Completed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Previous Status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("COMPLETED", "Completed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        max_length=20,
                        verbose_name="New Status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Status History",
                "verbose_name_plural": "Appointment Status Histories",
                "db_table": "consultations_appointment_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "consultation_summary",
                    models.TextField(verbose_name="Consultation Summary"),
                ),
                (
                    "clinical_observation",
                    models.TextField(verbose_name="Clinical Observation"),
                ),
                (
                    "doctor_recommendations",
                    models.TextField(verbose_name="Doctor Recommendations"),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "followup_required",
                    models.BooleanField(
                        default=False, verbose_name="Follow-up Required"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultation",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "db_table": "consultations_consultations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Weekday",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "db_table": "consultations_doctor_availabilities",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Patient Number"
                    ),
                ),
                (
                    "parent_first_name",
                    models.CharField(max_length=150, verbose_name="Parent First Name"),
                ),
                (
                    "parent_last_name",
                    models.CharField(max_length=150, verbose_name="Parent Last Name"),
                ),
                (
                    "relationship_to_child",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Relationship to Child",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=20, verbose_name="Mobile Number"),
                ),
                (
                    "alternate_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Alternate Mobile Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "child_first_name",
                    models.CharField(max_length=150, verbose_name="Child First Name"),
                ),
                (
                    "child_last_name",
                    models.CharField(max_length=150, verbose_name="Child Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Child Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "patient_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UNDER_TREATMENT", "Under Treatment"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("DISCHARGED", "Discharged"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                        verbose_name="Patient Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "consultations_patients",
                "ordering": ["child_last_name", "child_first_name"],
                "indexes": [
                    models.Index(fields=["mobile_number"], name="idx_patient_mobile"),
                    models.Index(
                        fields=["child_first_name"], name="idx_patient_first_name"
                    ),
                    models.Index(
                        fields=["child_last_name"], name="idx_patient_last_name"
                    ),
                    models.Index(fields=["date_of_birth"], name="idx_patient_dob"),
                ],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="consultations.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["status"], name="idx_apptreq_status"),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["mobile_number"], name="idx_apptreq_mobile"),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["preferred_date"], name="idx_apptreq_pref_date"),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(fields=["doctor"], name="idx_slot_doctor"),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(fields=["slot_date"], name="idx_slot_date"),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(fields=["status"], name="idx_slot_status"),
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "slot_date", "start_time", "end_time"),
                name="unique_doctor_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentstatushistory",
            index=models.Index(fields=["appointment"], name="idx_appthist_appt"),
        ),
        migrations.AddIndex(
            model_name="appointmentstatushistory",
            index=models.Index(fields=["new_status"], name="idx_appthist_status"),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(fields=["doctor"], name="idx_cons_doctor"),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["next_review_date"], name="idx_cons_next_review"
            ),
        ),
        migrations.AddIndex(
            model_name="doctoravailability",
            index=models.Index(fields=["doctor"], name="idx_docavail_doctor"),
        ),
        migrations.AddIndex(
            model_name="doctoravailability",
            index=models.Index(fields=["weekday"], name="idx_docavail_weekday"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["appointment_date"], name="idx_appt_date"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="idx_appt_status"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["patient"], name="idx_appt_patient"),
        ),
    ]
