# Generated by Django 5.2.9 on 2026-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("REVIEW", "Review"),
                    ("INITIAL_CONSULTATION", "Initial Consultation"),
                    ("DEVELOPMENT_ASSESSMENT", "Development Assessment"),
                ],
                max_length=50,
                verbose_name="Appointment Type",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("REVIEW", "Review"),
                    ("INITIAL_CONSULTATION", "Initial Consultation"),
                    ("DEVELOPMENT_ASSESSMENT", "Development Assessment"),
                ],
                max_length=50,
                verbose_name="Appointment Type",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT_TO_SAY", "Prefer Not To Say"),
                ],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="relationship_to_child",
            field=models.CharField(
                choices=[
                    ("FATHER", "Father"),
                    ("MOTHER", "Mother"),
                    ("GUARDIAN", "Guardian"),
                    ("GRANDPARENT", "Grandparent"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                verbose_name="Relationship to Child",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT_TO_SAY", "Prefer Not To Say"),
                ],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="relationship_to_child",
            field=models.CharField(
                choices=[
                    ("FATHER", "Father"),
                    ("MOTHER", "Mother"),
                    ("GUARDIAN", "Guardian"),
                    ("GRANDPARENT", "Grandparent"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                verbose_name="Relationship to Child",
            ),
        ),
    ]
