# Generated by Django 5.2.9 on 2026-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_alter_appointment_appointment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="referral_source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Referral Source"
            ),
        ),
    ]
