# Generated by Django 5.2.9 on 2026-06-27 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_appointmentrequest_referral_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_requests",
                to="consultations.patient",
                verbose_name="Linked/Created Patient",
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="patient_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Patient Created At"
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="patient_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patient_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient Created By",
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="patient_linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Patient Linked At"
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="patient_linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient Linked By",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PATIENT_LINKED", "Patient Linked"),
                    ("PATIENT_CREATED", "Patient Created"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["patient"], name="idx_apptreq_patient"),
        ),
    ]
