# Generated by Django 5.2.9 on 2026-06-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0004_appointmentrequest_patient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Doctor",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Emergency Contact Name",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Emergency Contact Phone",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="patient",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Medical Notes"),
        ),
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="patients/", verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_language",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Preferred Language"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="primary_diagnosis",
            field=models.TextField(
                blank=True, null=True, verbose_name="Primary Diagnosis"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="referral_source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Referral Source"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["is_deleted"], name="idx_patient_is_deleted"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["assigned_doctor"], name="idx_patient_doctor"),
        ),
    ]
