# Generated by Django 5.2.9 on 2026-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0005_patient_assigned_doctor_patient_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True, verbose_name="Allergies"),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Blood Group"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_focus",
            field=models.TextField(blank=True, null=True, verbose_name="Current Focus"),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_progress",
            field=models.TextField(
                blank=True, null=True, verbose_name="Current Progress"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_treatment_plan",
            field=models.TextField(
                blank=True, null=True, verbose_name="Current Treatment Plan"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Internal Notes"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="latest_recommendation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Latest Recommendation"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_alerts",
            field=models.TextField(
                blank=True, null=True, verbose_name="Medical Alerts"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="recommended_sessions",
            field=models.IntegerField(
                blank=True, default=10, null=True, verbose_name="Recommended Sessions"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="therapy_started",
            field=models.DateField(
                blank=True, null=True, verbose_name="Therapy Started"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="treatment_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Treatment Summary"
            ),
        ),
    ]
