# Generated by Django 5.2.9 on 2026-06-27 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0007_clinicholiday_doctorleave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("event", models.CharField(max_length=100, verbose_name="Event")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Appointment Timeline",
                "verbose_name_plural": "Appointment Timelines",
                "db_table": "consultations_appointment_timelines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                        verbose_name="Weekday",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Break Title")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
            ],
            options={
                "verbose_name": "Clinic Break",
                "verbose_name_plural": "Clinic Breaks",
                "db_table": "consultations_clinic_breaks",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic_name",
                    models.CharField(max_length=255, verbose_name="Clinic Name"),
                ),
                ("opening_time", models.TimeField(verbose_name="Opening Time")),
                ("closing_time", models.TimeField(verbose_name="Closing Time")),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Slot Duration (Minutes)"
                    ),
                ),
                (
                    "booking_window_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Booking Window (Days)"
                    ),
                ),
                (
                    "allow_same_day_booking",
                    models.BooleanField(
                        default=True, verbose_name="Allow Same Day Booking"
                    ),
                ),
                (
                    "max_daily_appointments",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Max Daily Appointments"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=100, verbose_name="Timezone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Settings",
                "verbose_name_plural": "Clinic Settings",
                "db_table": "consultations_clinic_settings",
            },
        ),
        migrations.CreateModel(
            name="ClinicWeeklySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Weekday",
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="Is Open")),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Weekly Schedule",
                "verbose_name_plural": "Clinic Weekly Schedules",
                "db_table": "consultations_clinic_weekly_schedules",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="DoctorBlockedSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("block_date", models.DateField(verbose_name="Block Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
            ],
            options={
                "verbose_name": "Doctor Blocked Slot",
                "verbose_name_plural": "Doctor Blocked Slots",
                "db_table": "consultations_doctor_blocked_slots",
                "ordering": ["block_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DoctorWorkingDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="Is Working"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
            ],
            options={
                "verbose_name": "Doctor Working Day",
                "verbose_name_plural": "Doctor Working Days",
                "db_table": "consultations_doctor_working_days",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
            },
        ),
        migrations.RemoveIndex(
            model_name="doctoravailability",
            name="idx_docavail_doctor",
        ),
        migrations.RemoveIndex(
            model_name="doctoravailability",
            name="idx_docavail_weekday",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="reason_for_visit",
            new_name="visit_reason",
        ),
        migrations.RenameField(
            model_name="clinicholiday",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="weekday",
        ),
        migrations.RemoveField(
            model_name="doctorleave",
            name="status",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Duration (Minutes)"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Internal Notes"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="MEDIUM",
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT", "Direct"),
                    ("DOCTOR_REFERRAL", "Doctor Referral"),
                    ("SCHOOL_REFERRAL", "School Referral"),
                    ("WEBSITE", "Website"),
                    ("SOCIAL_MEDIA", "Social Media"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Referral Source",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="visit_reason",
            field=models.TextField(blank=True, default="", verbose_name="Visit Reason"),
        ),
        migrations.AddField(
            model_name="clinicholiday",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="clinicholiday",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Holiday Title"
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="accepts_appointments",
            field=models.BooleanField(
                default=True, verbose_name="Accepts Appointments"
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="consultation_duration_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Consultation Duration (Minutes)"
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="max_daily_patients",
            field=models.PositiveIntegerField(
                default=15, verbose_name="Max Daily Patients"
            ),
        ),
        migrations.AddField(
            model_name="doctorleave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked In"),
                    ("IN_CONSULTATION", "In Consultation"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                default="CONFIRMED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked In"),
                    ("IN_CONSULTATION", "In Consultation"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                max_length=20,
                verbose_name="New Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentstatushistory",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked In"),
                    ("IN_CONSULTATION", "In Consultation"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                max_length=20,
                null=True,
                verbose_name="Previous Status",
            ),
        ),
        migrations.AlterField(
            model_name="clinicholiday",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["doctor"], name="idx_appt_doctor"),
        ),
        migrations.AddIndex(
            model_name="clinicholiday",
            index=models.Index(fields=["holiday_date"], name="idx_clinichol_date"),
        ),
        migrations.AddIndex(
            model_name="doctorleave",
            index=models.Index(
                fields=["doctor", "start_date", "end_date"],
                name="idx_docleave_doc_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="appointment_time_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="appointment_duration_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("consultation_duration_minutes__gt", 0)),
                name="doctor_consultation_duration_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_daily_patients__gte", 0)),
                name="doctor_max_daily_patients_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("doctor", "is_active"),
                name="unique_active_doctor_availability",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorleave",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="doctor_leave_date_check",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttimeline",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="consultations.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttimeline",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_timeline_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed By",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicbreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="clinic_break_time_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_clinic_settings",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_duration_minutes__gt", 0)),
                name="clinic_slot_duration_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("booking_window_days__gt", 0)),
                name="clinic_booking_window_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_daily_appointments__gt", 0)),
                name="clinic_max_daily_appointments_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicweeklyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_open", False),
                        models.Q(
                            ("closing_time__gt", models.F("opening_time")),
                            ("is_open", True),
                        ),
                        _connector="OR",
                    )
                ),
                name="clinic_weekly_schedule_time_check",
            ),
        ),
        migrations.AddField(
            model_name="doctorblockedslot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_blocked_slots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="doctorblockedslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_slots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="doctorworkingday",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_days",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorblockedslot",
            index=models.Index(
                fields=["doctor", "block_date"], name="idx_docblock_doc_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorblockedslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="doctor_blocked_time_check",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorworkingday",
            index=models.Index(
                fields=["doctor", "weekday"], name="idx_docwork_doc_wkday"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorworkingday",
            constraint=models.UniqueConstraint(
                fields=("doctor", "weekday"), name="unique_doctor_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorworkingday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_working", False),
                        models.Q(
                            ("end_time__gt", models.F("start_time")),
                            ("is_working", True),
                        ),
                        _connector="OR",
                    )
                ),
                name="doctor_working_day_time_check",
            ),
        ),
    ]
