# Generated by Django 5.2.15 on 2026-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0008_appointmenttimeline_clinicbreak_clinicsettings_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicbreak",
            name="title",
        ),
        migrations.RemoveField(
            model_name="clinicholiday",
            name="title",
        ),
        migrations.AddField(
            model_name="clinicbreak",
            name="break_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Break Title"
            ),
        ),
        migrations.AddField(
            model_name="clinicholiday",
            name="holiday_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Holiday Name"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="clinic_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clinic_logos/",
                verbose_name="Clinic Logo",
            ),
        ),
        migrations.AlterField(
            model_name="clinicholiday",
            name="holiday_date",
            field=models.DateField(verbose_name="Holiday Date"),
        ),
        migrations.AddConstraint(
            model_name="clinicholiday",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("holiday_date",),
                name="unique_active_holiday_date",
            ),
        ),
    ]
