# Generated by Django 5.2.15 on 2026-06-28 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0009_remove_clinicbreak_title_remove_clinicholiday_title_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("event", models.CharField(max_length=100, verbose_name="Event")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="consultations.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Timeline",
                "verbose_name_plural": "Patient Timelines",
                "db_table": "consultations_patient_timelines",
                "ordering": ["created_at"],
            },
        ),
    ]
