# Generated by Django 5.2.15 on 2026-06-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0010_patienttimeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PATIENT_LINKED", "Patient Linked"),
                    ("PATIENT_CREATED", "Patient Created"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
