# Generated by Django 5.2.15 on 2026-06-28 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0011_alter_appointmentrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="chief_complaint",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Chief Complaint"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="clinical_findings",
            field=models.TextField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Clinical Findings",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="diagnosis",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Diagnosis"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Is Completed"),
        ),
        migrations.AddField(
            model_name="consultation",
            name="recommendations",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="Recommendations"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="treatment_notes",
            field=models.TextField(
                blank=True, max_length=10000, null=True, verbose_name="Treatment Notes"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="clinical_observation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Clinical Observation"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Consultation Summary"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="doctor_recommendations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Doctor Recommendations"
            ),
        ),
        migrations.CreateModel(
            name="ConsultationActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "old_values",
                    models.JSONField(blank=True, null=True, verbose_name="Old Values"),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="New Values"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_activity_logs",
                        to="consultations.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="consultations.consultation",
                        verbose_name="Consultation",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_activity_logs",
                        to="consultations.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Activity Log",
                "verbose_name_plural": "Consultation Activity Logs",
                "db_table": "consultations_consultation_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="consultation_attachments/",
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Original Name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File Size (Bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="consultations.consultation",
                        verbose_name="Consultation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_consultation_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Attachment",
                "verbose_name_plural": "Consultation Attachments",
                "db_table": "consultations_consultation_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Field Name"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Old Value"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="New Value"),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="consultations.consultation",
                        verbose_name="Consultation",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Audit Log",
                "verbose_name_plural": "Consultation Audit Logs",
                "db_table": "consultations_consultation_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
