# Generated by Django 5.2.15 on 2026-06-28 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0012_consultation_chief_complaint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="previous_consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_appointments",
                to="consultations.consultation",
                verbose_name="Previous Consultation",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="previous_consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_consultations",
                to="consultations.consultation",
                verbose_name="Previous Consultation",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="requires_followup",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Requires Follow-up"
            ),
        ),
        migrations.CreateModel(
            name="TreatmentCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FOLLOW_UP_REQUIRED", "Follow-up Required"),
                            ("FOLLOW_UP_SCHEDULED", "Follow-up Scheduled"),
                            ("FOLLOW_UP_COMPLETED", "Follow-up Completed"),
                            ("CASE_CLOSED", "Case Closed"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Primary Diagnosis",
                    ),
                ),
                (
                    "closing_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="Closing Summary"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Outcome"
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reopen Reason"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_cases",
                        to="consultations.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Case",
                "verbose_name_plural": "Treatment Cases",
                "db_table": "consultations_treatment_cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="treatment_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="consultations.treatmentcase",
                verbose_name="Treatment Case",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="treatment_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultations",
                to="consultations.treatmentcase",
                verbose_name="Treatment Case",
            ),
        ),
    ]
