# Generated by Django 5.2.15 on 2026-07-02 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0013_appointment_previous_consultation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentRequestActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "old_values",
                    models.JSONField(blank=True, null=True, verbose_name="Old Values"),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="New Values"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Browser"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Booking Source",
                    ),
                ),
                (
                    "appointment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="consultations.appointmentrequest",
                        verbose_name="Appointment Request",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_request_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Request Activity Log",
                "verbose_name_plural": "Appointment Request Activity Logs",
                "db_table": "consultations_appointment_request_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentRequestTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_code",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Request Submitted"),
                            ("VIEWED", "Viewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PATIENT_CREATED", "Patient Created"),
                            ("PATIENT_LINKED", "Patient Linked"),
                            ("APPOINTMENT_CREATED", "Appointment Created"),
                            ("SUMMARY_PRINTED", "Summary Printed"),
                            ("EXPORTED", "Exported"),
                            ("NOTES_ADDED", "Notes Added"),
                        ],
                        max_length=50,
                        verbose_name="Event Code",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Color"
                    ),
                ),
                (
                    "appointment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="consultations.appointmentrequest",
                        verbose_name="Appointment Request",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_request_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Request Timeline",
                "verbose_name_plural": "Appointment Request Timelines",
                "db_table": "consultations_appointment_request_timelines",
                "ordering": ["created_at"],
            },
        ),
    ]
