class ActivityType:
    # Authentication Events
    LOGIN = 'LOGIN'
    LOGOUT = 'LOGOUT'
    FAILED_LOGIN = 'FAILED_LOGIN'
    PASSWORD_RESET = 'PASSWORD_RESET'
    PASSWORD_CHANGED = 'PASSWORD_CHANGED'
    OTP_VERIFIED = 'OTP_VERIFIED'

    # Administrative Events
    USER_CREATED = 'USER_CREATED'
    USER_UPDATED = 'USER_UPDATED'
    USER_LOCKED = 'USER_LOCKED'
    USER_UNLOCKED = 'USER_UNLOCKED'
    USER_DELETED = 'USER_DELETED'
    ROLE_ASSIGNED = 'ROLE_ASSIGNED'
    ROLE_REMOVED = 'ROLE_REMOVED'
    USER_DISABLED = 'USER_DISABLED'

    # Security Events
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED'
    SESSION_REVOKED = 'SESSION_REVOKED'

    # Hardening Events
    ROLE_SEEDED = 'ROLE_SEEDED'
    INITIAL_ADMIN_CREATED = 'INITIAL_ADMIN_CREATED'
    ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED'
    EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT'
    EMAIL_VERIFIED = 'EMAIL_VERIFIED'
    CONSULTATION_REQUEST_CREATED = 'CONSULTATION_REQUEST_CREATED'
    APPOINTMENT_REQUEST_VIEWED = 'APPOINTMENT_REQUEST_VIEWED'
    APPOINTMENT_REQUEST_APPROVED = 'APPOINTMENT_REQUEST_APPROVED'
    APPOINTMENT_REQUEST_REJECTED = 'APPOINTMENT_REQUEST_REJECTED'
    PATIENT_MATCHING_STARTED = 'PATIENT_MATCHING_STARTED'
    PATIENT_LINKED = 'PATIENT_LINKED'
    PATIENT_CREATED = 'PATIENT_CREATED'
    PATIENT_UPDATED = 'PATIENT_UPDATED'
    PATIENT_DELETED = 'PATIENT_DELETED'
    PATIENT_EXPORTED = 'PATIENT_EXPORTED'
    PATIENT_ASSIGNED_DOCTOR = 'PATIENT_ASSIGNED_DOCTOR'
    PATIENT_STATUS_CHANGED = 'PATIENT_STATUS_CHANGED'
    PATIENT_SEARCHED = 'PATIENT_SEARCHED'
    PATIENT_PREVIEW_VIEWED = 'PATIENT_PREVIEW_VIEWED'
    PATIENT_PROFILE_VIEWED = 'PATIENT_PROFILE_VIEWED'
    PARENT_INFORMATION_UPDATED = 'PARENT_INFORMATION_UPDATED'
    CHILD_INFORMATION_UPDATED = 'CHILD_INFORMATION_UPDATED'
    PATIENT_INFORMATION_UPDATED = 'PATIENT_INFORMATION_UPDATED'
    PATIENT_TIMELINE_VIEWED = 'PATIENT_TIMELINE_VIEWED'

    # Appointment Creation events
    APPOINTMENT_CREATED = 'APPOINTMENT_CREATED'
    APPOINTMENT_PREVIEWED = 'APPOINTMENT_PREVIEWED'
    APPOINTMENT_SLOT_VALIDATED = 'APPOINTMENT_SLOT_VALIDATED'
    DOCTOR_AVAILABILITY_VIEWED = 'DOCTOR_AVAILABILITY_VIEWED'
    SLOTS_FETCHED = 'SLOTS_FETCHED'

    # Clinic configuration events
    CLINIC_SETTINGS_UPDATED = 'CLINIC_SETTINGS_UPDATED'
    WEEKLY_SCHEDULE_UPDATED = 'WEEKLY_SCHEDULE_UPDATED'
    CLINIC_HOLIDAY_CREATED = 'CLINIC_HOLIDAY_CREATED'
    CLINIC_HOLIDAY_UPDATED = 'CLINIC_HOLIDAY_UPDATED'
    CLINIC_HOLIDAY_DELETED = 'CLINIC_HOLIDAY_DELETED'
    CLINIC_BREAK_CREATED = 'CLINIC_BREAK_CREATED'
    CLINIC_BREAK_UPDATED = 'CLINIC_BREAK_UPDATED'
    CLINIC_BREAK_DELETED = 'CLINIC_BREAK_DELETED'

    # Doctor configuration events
    DOCTOR_AVAILABILITY_UPDATED = 'DOCTOR_AVAILABILITY_UPDATED'
    DOCTOR_WORKING_DAYS_UPDATED = 'DOCTOR_WORKING_DAYS_UPDATED'
    DOCTOR_LEAVE_CREATED = 'DOCTOR_LEAVE_CREATED'
    DOCTOR_LEAVE_UPDATED = 'DOCTOR_LEAVE_UPDATED'
    DOCTOR_LEAVE_DELETED = 'DOCTOR_LEAVE_DELETED'
    DOCTOR_BLOCKED_SLOT_CREATED = 'DOCTOR_BLOCKED_SLOT_CREATED'
    DOCTOR_BLOCKED_SLOT_UPDATED = 'DOCTOR_BLOCKED_SLOT_UPDATED'
    DOCTOR_BLOCKED_SLOT_DELETED = 'DOCTOR_BLOCKED_SLOT_DELETED'

    APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED'
    APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED'
    APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED'
    APPOINTMENT_CHECKED_IN = 'APPOINTMENT_CHECKED_IN'
    APPOINTMENT_IN_CONSULTATION = 'APPOINTMENT_IN_CONSULTATION'
    APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW'

    # Consultation Events
    CONSULTATION_CREATED = 'CONSULTATION_CREATED'
    CONSULTATION_UPDATED = 'CONSULTATION_UPDATED'
    CONSULTATION_ATTACHMENT_UPLOADED = 'CONSULTATION_ATTACHMENT_UPLOADED'
    CONSULTATION_ATTACHMENT_DELETED = 'CONSULTATION_ATTACHMENT_DELETED'
    CONSULTATION_COMPLETED = 'CONSULTATION_COMPLETED'

    # Follow-up & Treatment Case Events
    FOLLOW_UP_DECISION_RECORDED = 'FOLLOW_UP_DECISION_RECORDED'
    FOLLOW_UP_CREATED = 'FOLLOW_UP_CREATED'
    FOLLOW_UP_UPDATED = 'FOLLOW_UP_UPDATED'
    FOLLOW_UP_CANCELLED = 'FOLLOW_UP_CANCELLED'
    TREATMENT_CASE_CLOSED = 'TREATMENT_CASE_CLOSED'
    TREATMENT_CASE_REOPENED = 'TREATMENT_CASE_REOPENED'

    CHOICES = [
        (LOGIN, 'Login'),
        (LOGOUT, 'Logout'),
        (FAILED_LOGIN, 'Failed Login'),
        (PASSWORD_RESET, 'Password Reset'),
        (PASSWORD_CHANGED, 'Password Changed'),
        (OTP_VERIFIED, 'OTP Verified'),
        (USER_CREATED, 'User Created'),
        (USER_UPDATED, 'User Updated'),
        (USER_LOCKED, 'User Locked'),
        (USER_UNLOCKED, 'User Unlocked'),
        (USER_DELETED, 'User Deleted'),
        (ROLE_ASSIGNED, 'Role Assigned'),
        (ROLE_REMOVED, 'Role Removed'),
        (USER_DISABLED, 'User Disabled'),
        (ACCOUNT_LOCKED, 'Account Locked'),
        (SESSION_REVOKED, 'Session Revoked'),
        (ROLE_SEEDED, 'Role Seeded'),
        (INITIAL_ADMIN_CREATED, 'Initial Admin Created'),
        (ACCOUNT_UNLOCKED, 'Account Unlocked'),
        (EMAIL_VERIFICATION_SENT, 'Email Verification Sent'),
        (EMAIL_VERIFIED, 'Email Verified'),
        (CONSULTATION_REQUEST_CREATED, 'Consultation Request Created'),
        (APPOINTMENT_REQUEST_VIEWED, 'Appointment Request Viewed'),
        (APPOINTMENT_REQUEST_APPROVED, 'Appointment Request Approved'),
        (APPOINTMENT_REQUEST_REJECTED, 'Appointment Request Rejected'),
        (PATIENT_MATCHING_STARTED, 'Patient Matching Started'),
        (PATIENT_LINKED, 'Patient Linked'),
        (PATIENT_CREATED, 'Patient Created'),
        (PATIENT_UPDATED, 'Patient Updated'),
        (PATIENT_DELETED, 'Patient Deleted'),
        (PATIENT_EXPORTED, 'Patient Exported'),
        (PATIENT_ASSIGNED_DOCTOR, 'Patient Assigned Doctor'),
        (PATIENT_STATUS_CHANGED, 'Patient Status Changed'),
        (PATIENT_SEARCHED, 'Patient Searched'),
        (PATIENT_PREVIEW_VIEWED, 'Patient Preview Viewed'),
        (PATIENT_PROFILE_VIEWED, 'Patient Profile Viewed'),
        (PARENT_INFORMATION_UPDATED, 'Parent Information Updated'),
        (CHILD_INFORMATION_UPDATED, 'Child Information Updated'),
        (PATIENT_INFORMATION_UPDATED, 'Patient Information Updated'),
        (PATIENT_TIMELINE_VIEWED, 'Patient Timeline Viewed'),
        (APPOINTMENT_CREATED, 'Appointment Created'),
        (APPOINTMENT_PREVIEWED, 'Appointment Previewed'),
        (APPOINTMENT_SLOT_VALIDATED, 'Appointment Slot Validated'),
        (DOCTOR_AVAILABILITY_VIEWED, 'Doctor Availability Viewed'),
        (SLOTS_FETCHED, 'Slots Fetched'),
        (CLINIC_SETTINGS_UPDATED, 'Clinic Settings Updated'),
        (WEEKLY_SCHEDULE_UPDATED, 'Weekly Schedule Updated'),
        (CLINIC_HOLIDAY_CREATED, 'Clinic Holiday Created'),
        (CLINIC_HOLIDAY_UPDATED, 'Clinic Holiday Updated'),
        (CLINIC_HOLIDAY_DELETED, 'Clinic Holiday Deleted'),
        (CLINIC_BREAK_CREATED, 'Clinic Break Created'),
        (CLINIC_BREAK_UPDATED, 'Clinic Break Updated'),
        (CLINIC_BREAK_DELETED, 'Clinic Break Deleted'),
        (DOCTOR_AVAILABILITY_UPDATED, 'Doctor Availability Updated'),
        (DOCTOR_WORKING_DAYS_UPDATED, 'Doctor Working Days Updated'),
        (DOCTOR_LEAVE_CREATED, 'Doctor Leave Created'),
        (DOCTOR_LEAVE_UPDATED, 'Doctor Leave Updated'),
        (DOCTOR_LEAVE_DELETED, 'Doctor Leave Deleted'),
        (DOCTOR_BLOCKED_SLOT_CREATED, 'Doctor Blocked Slot Created'),
        (DOCTOR_BLOCKED_SLOT_UPDATED, 'Doctor Blocked Slot Updated'),
        (DOCTOR_BLOCKED_SLOT_DELETED, 'Doctor Blocked Slot Deleted'),
        (APPOINTMENT_UPDATED, 'Appointment Updated'),
        (APPOINTMENT_RESCHEDULED, 'Appointment Rescheduled'),
        (APPOINTMENT_CANCELLED, 'Appointment Cancelled'),
        (APPOINTMENT_CHECKED_IN, 'Appointment Checked In'),
        (APPOINTMENT_IN_CONSULTATION, 'Appointment In Consultation'),
        (APPOINTMENT_NO_SHOW, 'Appointment No Show'),
        (CONSULTATION_CREATED, 'Consultation Created'),
        (CONSULTATION_UPDATED, 'Consultation Updated'),
        (CONSULTATION_ATTACHMENT_UPLOADED, 'Consultation Attachment Uploaded'),
        (CONSULTATION_ATTACHMENT_DELETED, 'Consultation Attachment Deleted'),
        (CONSULTATION_COMPLETED, 'Consultation Completed'),
        (FOLLOW_UP_DECISION_RECORDED, 'Follow-up Decision Recorded'),
        (FOLLOW_UP_CREATED, 'Follow-up Created'),
        (FOLLOW_UP_UPDATED, 'Follow-up Updated'),
        (FOLLOW_UP_CANCELLED, 'Follow-up Cancelled'),
        (TREATMENT_CASE_CLOSED, 'Treatment Case Closed'),
        (TREATMENT_CASE_REOPENED, 'Treatment Case Reopened'),
    ]
